[package]
name = "tutorial"
version = "0.1.0"
authors = ["Joakim Ohlander <joxxor@gmail.com>"]
edition = "2018"
RUST_BACKTRACE=1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
panic = 'abort'